# Generated by Django 6.0.1 on 2026-01-27 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
        ('product', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='started_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='alert',
            name='triggered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('product', 'target_price')},
        ),
    ]
