# Generated by Django 6.0.1 on 2026-03-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
        ('product', '0002_remove_product_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='product_target_price_constraint',
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('product', 'target_price', 'user'), name='product_target_price_constraint', violation_error_message='You already have a track with this product and this target price.'),
        ),
    ]
