# Generated by Django 6.0.1 on 2026-02-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alert_started_price_alert_triggered_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='started_price_eur',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='triggered_price_eur',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
