# Generated by Django 6.0.1 on 2026-03-11 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_archivealert_user'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='product_target_price_constraint',
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('product', 'target_price', 'user'), name='product_target_price_constraint'),
        ),
    ]
