# Generated by Django 6.0.1 on 2026-03-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_archivealert_user'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='product.product'),
        ),
    ]
