# Generated by Django 6.0.1 on 2026-02-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_started_price_eur_alert_triggered_price_eur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='started_price',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='started_price_eur',
        ),
    ]
