# Generated by Django 6.0.1 on 2026-03-11 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_remove_alert_product_target_price_constraint_and_more'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='alert',
            name='product_target_price_constraint',
            constraint=models.UniqueConstraint(fields=('product', 'target_price', 'user'), name='product_target_price_constraint', violation_error_message='You already have a track with this product and this target price.'),
        ),
    ]
