# Generated by Django 6.0.1 on 2026-02-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_alert_started_price_alert_started_price_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
