# Generated by Django 6.0.1 on 2026-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_alert_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
