# Generated by Django 6.0.1 on 2026-02-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_alter_alert_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
