# Generated by Django 6.0.1 on 2026-02-05 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_alter_alert_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('started_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.02)])),
                ('product_currency', models.TextField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='EUR', max_length=3)),
                ('started_price_eur', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('triggered_price_eur', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('alert_created_at', models.DateTimeField()),
                ('alert_finished_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='started_price_eur',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='triggered_price_eur',
        ),
        migrations.AlterField(
            model_name='alert',
            name='started_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.02)]),
        ),
    ]
