# Generated by Django 6.0.1 on 2026-02-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_archivealert_remove_alert_started_price_eur_and_more'),
        ('product', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('target_price__lt', models.F('started_price'))), name='target_price_lt_started_price'),
        ),
    ]
