# Generated by Django 6.0.1 on 2026-02-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0010_alert_target_price_lt_started_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='target_price_lt_started_price',
        ),
    ]
