# Generated by Django 6.0.1 on 2026-02-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0011_remove_alert_target_price_lt_started_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='counter_checks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
