# Generated by Django 6.0.1 on 2026-02-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0012_alert_counter_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivealert',
            name='counter_checks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivealert',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
