# Generated by Django 6.0.1 on 2026-02-09 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0013_archivealert_counter_checks_archivealert_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivealert',
            name='category_title',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
