# Generated by Django 6.0.1 on 2026-02-09 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0014_archivealert_category_title'),
        ('catalog', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivealert',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.category'),
        ),
    ]
