# Generated by Django 6.0.1 on 2026-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0015_archivealert_category'),
        ('product', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivealert',
            options={'ordering': ['-alert_finished_at']},
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('product', 'target_price'), name='product_target_price_constraint'),
        ),
    ]
