# Generated by Django 6.0.1 on 2026-02-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0016_alter_archivealert_options_and_more'),
        ('catalog', '0004_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivealert',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='catalog.category'),
        ),
    ]
