# Generated by Django 6.0.1 on 2026-02-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0017_alter_archivealert_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alert.alert')),
            ],
            options={
                'ordering': ['checked_at'],
            },
        ),
    ]
