# Generated by Django 6.0.1 on 2026-02-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0018_pricetimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTimelineArchived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('history_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_alerts', to='alert.archivealert')),
            ],
        ),
    ]
