# Generated by Django 6.0.1 on 2026-02-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0019_pricetimelinearchived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetimeline',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_timelines', to='alert.alert'),
        ),
    ]
