# Generated by Django 6.0.1 on 2026-02-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0020_alter_pricetimeline_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetimelinearchived',
            name='checked_at',
            field=models.DateTimeField(),
        ),
    ]
