# Generated by Django 6.0.1 on 2026-02-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0021_alter_pricetimelinearchived_checked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='counter_checks',
        ),
    ]
