# Generated by Django 6.0.1 on 2026-02-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0022_remove_alert_counter_checks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivealert',
            name='counter_checks',
        ),
    ]
