# Generated by Django 6.0.1 on 2026-02-24 12:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0024_alter_alert_started_price_alter_alert_target_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='started_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
