# Generated by Django 6.0.1 on 2026-04-03 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('product', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('url', 'store', 'title'), name='product_unique_constraint', violation_error_message='Our application already has this product from the selected store'),
        ),
    ]
