# Generated by Django 6.0.1 on 2026-02-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='EUR', max_length=3),
        ),
    ]
