# Generated by Django 6.0.1 on 2026-02-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_started_price_product_started_price_eur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='started_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='started_price_eur',
        ),
    ]
