# Generated by Django 6.0.1 on 2026-02-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_description'),
        ('product', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='choose a tag or create your own', related_name='products', to='catalog.tag'),
        ),
    ]
