# Generated by Django 6.0.1 on 2026-03-04 18:05

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', accounts.managers.AppUserManager()),
            ],
        ),
    ]
