# Generated by Django 6.0.1 on 2026-03-09 08:02

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', accounts.managers.AppUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
