# Generated by Django 6.0.1 on 2026-04-03 08:31

from django.db import migrations

def create_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    moderator, _ = Group.objects.get_or_create(name='Moderator')  # (object, created)
    moderator_list_perms = ['add_category','change_category', 'delete_category', 'delete_tag', 'change_product','add_store', 'change_store', 'delete_store', 'view_store']
    moderator_perms = Permission.objects.filter(codename__in=moderator_list_perms)
    moderator.permissions.set(moderator_perms)

    user_manager, _ = Group.objects.get_or_create(name='AppUser-manager')
    user_manager_list_perms = ['delete_appuser', 'view_appuser', 'delete_profile', 'view_profile', 'view_archivealert']
    user_manager_perms = Permission.objects.filter(codename__in=user_manager_list_perms)
    user_manager.permissions.set(user_manager_perms)


def remove_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Moderator', 'AppUser-manager']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_group, remove_group)
    ]
