# Generated by Django 6.0.1 on 2026-04-06 17:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='card_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
